# Generated by Django 4.1.5 on 2023-04-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
